src/And6a/UserBundle/Entity/User.php
<?php
// src/And6a/UserBundle/Entity/User.php

namespace And6a\UserBundle\Entity;

use FOS\UserBundle\Entity\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
  /**
   * @ORM\Id
   * @ORM\Column(type="integer")
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  protected $id;

  /**
   * @ORM\Column(type="string", length="255", nullable="true")
   */
  protected $name;

  /**
   * @ORM\Column(type="string", length="255", nullable="true")
   */
  protected $fname;

  /**
   * @ORM\Column(type="date", nullable="true")
   */
  protected $birthday;

  /**
   * @ORM\Column(type="string", length="255", nullable="true")
   */
  protected $avatar;

  /**
   * @ORM\OneToMany(targetEntity="\And6a\TrombiBundle\Entity\GroupsUser", mappedBy="users", cascade={"persist"})
   */
  protected $class_groups;

   /**
   * @ORM\ManyToMany(targetEntity="\And6a\UserBundle\Entity\User", inversedBy="filleuls")
   * @ORM\JoinTable(name="user_parrains")
   */
  protected $parrains;

  /**
   * @ORM\ManyToMany(targetEntity="\And6a\UserBundle\Entity\User", mappedBy="parrains")
   */
  protected $filleuls;

  /**
   * @ORM\OneToMany(targetEntity="\And6a\UserBundle\Entity\Contact", mappedBy="user", cascade={"persist"})
   */
  protected $contacts = null;
  

  public function __construct()
  {
    parent::__construct();
    $this->users = new \Doctrine\Common\Collections\ArrayCollection();

    // your own logic

  }

  /**
   * Add gruops
   *
   * @param And6a\TrombiBundle\Entity\GroupsUser $groups
   */
  public function addGroupsUser(\And6a\TrombiBundle\Entity\GroupsUser $groups)
  {
    $this->class_groups[] = $groups;
  }


  /**
   * Get groups
   *
   * @return Doctrine\Common\Collections\Collection 
   */
  public function getGroupsUser()
  {
    return $this->class_groups;
  }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set fname
     *
     * @param string $fname
     */
    public function setFname($fname)
    {
        $this->fname = $fname;
    }

    /**
     * Get fname
     *
     * @return string 
     */
    public function getFname()
    {
        return $this->fname;
    }

    /**
     * Add infos
     *
     * @param And6a\UserBundle\Entity\Contact $infos
     */
    public function addContact(\And6a\UserBundle\Entity\Contact $contacts)
    {
        $this->contacts[] = $contacts;
    }

    /**
     * Get contacts
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getContacts()
    {
        return $this->contacts;
    }

    /**
     * Set birthday
     *
     * @param date $birthday
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;
    }

    /**
     * Get birthday
     *
     * @return date 
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Set contacts
     *
     * @param string $contacts
     */
    public function setContacts($contacts)
    {
        $this->contacts = $contacts;
    }
    
    public function __toString()
    {
      if( empty($this->name) && empty($this->fname) )
        return implode('.', array_reverse(explode('.', $this->username)));
      else
        return strtoupper($this->name) . ' ' . $this->fname;
    }

    /**
     * Get class_groups
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getClassGroups()
    {
        return $this->class_groups;
    }

    /**
     * Get current
     *
     * @return And6a\TrombiBundle\Entity\GroupsUser 
     */
    public function getCurrent()
    {
      $current = null;
      
      foreach( $this -> class_groups as $groups )
        if( $groups->getGroups()->getIsClass() )
          if( empty($current) || $groups->getYear() > $current->getYear() )
            $current = $groups;
      return $current;
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
    }

    /**
     * Get avatar
     *
     * @return string 
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    public function getUrlAvatar()
    {
      if( $this->avatar )
        return 'uploads/avatar/' . $this->avatar;
      return null;
    }

    /**
     * Add parrain
     *
     * @param And6a\UserBundle\Entity\User $parrain
     */
    public function addUser(\And6a\UserBundle\Entity\User $parrain)
    {
        $this->parrain[] = $parrain;
    }

    /**
     * Get parrains
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getParrains()
    {
        return $this->parrains;
    }

    /**
     * Set parrains
     *
     * @param And6a\UserBundle\Entity\User $parrains
     */
    public function setParrains(\And6a\UserBundle\Entity\User $parrains)
    {
        $this->parrains = $parrains;
    }

    /**
     * Get filleuls
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getFilleuls()
    {
        return $this->filleuls;
    }
}

src/And6a/UserBundle/Controller/DefaultController.php
<?php

namespace And6a\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use And6a\UserBundle\Entity\User as User;

class DefaultController extends Controller
{
  public function viewAction(User $user)
  { 
    $timeline = array();
    $i = 0;
    foreach( $user->getGroupsUser() as $groups )
    {
      $timeline[$groups->getYear()][$groups->getGroups()->getIsClass() . $i++] = $groups;
    }
    
    return $this->render('And6aUserBundle:Default:view.html.twig', array(
      'user' => $user,
      'timeline' => $timeline,
    ));
  }

  public function avatarAction()
  {
    $utilisateur= $this->container->get('security.context')->getToken()->getUser();
    
    //create a simple form with one filed called "dataFile" of type "file"
    $form = $this->get('form.factory')
   ->createBuilder('form')
   ->add('avatar', 'file', array('required' => true))
   ->getForm();

    $request = $this->get('request');
    if ($request->getMethod() == 'POST') {
        //bind the request, (note the enctype in the template)
        $form->bindRequest($request); 

      if ($form->isValid()) {
            //if the form is valid, try to get the uploaded file object
            //Symfony\Component\HttpFoundation\File\UploadedFile
          $files=$request->files->get($form->getName());
          
          //die(EntityDump(array($files['avatar']), 1));

          $uploadedFile=$files['avatar']; //"dataFile" is the name on the field
          

          //once you have the uploadedFile object there is some sweet functions you can run
          $uploadedFile->getPath();//returns current (temporary) path
          $name = $uploadedFile->getClientOriginalName();
          $ext = pathinfo($name, PATHINFO_EXTENSION);
          
          
          $user = $this->getDoctrine()->getRepository('And6aUserBundle:User')->findOneById($utilisateur->getId());
          //and most important is move(),
          $uploadedFile->move(
            $dir = __DIR__.'/../../../../web/uploads/avatar',
            $file = $utilisateur->getId() . '.' . $ext
          );

          $user->setAvatar($file);
          $em = $this->getDoctrine()->getEntityManager();
          $em->persist($user);
          $em->flush();

          $this->get('session')->setFlash('notice', 'The file is uploaded !');
      }
      else{
        //form is not valid
      }
    }//end if request method == POST  

    return $this->render('And6aUserBundle:Default:avatar.html.twig', array(
      'form'=>$form->createView(),
      'img_avatar' => 'uploads/avatar/' . $utilisateur->getAvatar(),
    ));
  }

  public function getBadgeAction($user = null, $style = 'badge', $withLink = true)
  {
    //if( (!is_object($user) || !$user->getId()) )
    //  $user = $this->getDoctrine()->getRepository('And6aUserBundle:User')->findOneById(is_array($user) ? $user['id'] : $user);

    //$user['avatar'] = 'bundles/and6auser/images/empty-avatar.png';
    //EntityDump($user);
    return $this->render('And6aUserBundle:Default:badge.html.twig', array(
  		'user'  => $user,
  		'style' => $style,
  		'withLink' => $withLink,
	  ));
  }
}

src/And6a/UserBundle/Resources/views/Default/avatar.html.twig
{% extends "And6aUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{# note the form_enctype, without it the form will not bind in the controller #}

<header>
  <h1>Modification de l'avatar</h1>
</header>

<div class="row">
  <div class="span8">
    <form action="" method="post" class="form form-horizontal" {{ form_enctype(form) }}>
      {{ form_widget(form, {show_legend: 0}) }}
      <div class="t-center">
          <button type="submit" class="btn btn-primary">Envoyer</button>
      </div>
    </form>
  </div>
  <div class="span4 well" style="text-align: center;">
    {% if app.user.avatar %}
    <img src="{{ asset(img_avatar) }}" alt="Avatar" style="max-height: 200px; max-width: 200px;" />
    {% else %}
    <img src="{{ asset('img/avatar-default.png') }}" alt="Pas d'avatar" />
    {% endif %}
  </div>
</div>
{% endblock %}

src/And6a/UserBundle/Resources/views/Default/badge.html.twig
{%if withLink %}
<a href="{{ path('And6aTrombiBundle_user_go', {id: user.id}) }}">
{%endif%}
  <figure class="user user-{{style|default('badge')}}">
    {% set avatar = user.urlAvatar|default('bundles/and6auser/images/empty-avatar.png') %}
    <img src="{{ asset(avatar) }}" />
    <figcaption>
      <span class="name">{{user}}</span>
      {% if not(user.current is empty) %}
      <span class="class">
        {{user.current.year}}
        ({%if user.current.year < "now"|date('Y') %}&infin;{%else%}{{user.current.level}}A{%endif%})
      </span>
      {% endif %}
    </figcation>
  </figure>
{%if withLink %}
</a>
{%endif%}

src/And6a/UserBundle/Resources/views/Default/index.html.twig
Hello {{ name }}!

src/And6a/UserBundle/Resources/views/Default/view.html.twig
{% extends '::layout.html.twig' %}

{% block body %}
  <h1>{{ user }} ({{user.current.level|default('?')}}A - {{user.current.groups.slug|default('?')|upper}})</h1>


  <div style="position: absolute; top: 2em;  right: 2em; width: 200px; text-align: center;">
    {% set avatar = user.urlAvatar|default(asset('img/avatar-default.png')) %}
    <img src="{{ asset(avatar) }}" class="avatar" />
  </div>

  <dl class="dl-horizontal dl-space">
    <dt>Nom</dt>
    <dd>{{ user.name }}</dd>

    <dt>Prénom</dt>
    <dd>{{ user.fname }}</dd>

    <dt>Né le</dt>
    <dd>{% if user.birthday %} {{ user.birthday|date('j/m/Y') }} (~ {{ ('now'|date('Y')) - (user.birthday|date('Y')) }} ans) {% endif %}</dd>
  </dl>

  <br style="clear: both"/>

  <hr />

  <h2>Ses informations</h2>
  <dl class="dl-horizontal dl-space">
  {% for info in user.contacts %}
    {% if app.user == user %}
    <dt>
      <a href="{{ path('contact_edit', {id: info.id}) }}" class="editable">
        {{ ('infos.contact.' ~ info.type)|trans({}, 'messages') }}
      </a>
    </dt>
    <dd>
      <a href="{{ path('contact_edit', {id: info.id}) }}" class="editable">
        {{info.value}}
        {%if info.private == 1 %}<b class="icon-eye-close" title="Donnée privée"></b>{% endif %}
      </a>
    </dd>
    {% else %}
    <dt>
      {{ ('infos.contact.' ~ info.type)|trans({}, 'messages') }}
    </dt>
    <dd>
      {{info.value}}
    </dd>
    {% endif %}

  {% endfor %}
  </dl>
  <br style="clear: both"/>

  <hr />

  <h2>Son parcours</h2>
  <dl class="dl-horizontal dl-space">
    {% for year, item in timeline %}
    <dt style="margin-right: 1em">{{ year }}</dt>
      {% for group in item %}
    <dd class="class">
      <a href="{{ path('And6aTrombiBundle_user_list', {group: group.groups.slug, year: year}) }}" class="btn {% if group.groups.isclass %}btn-success{% endif %}">
        <strong style="font-size: .75em">
          {{group.groups.name}}
          {% if group.level %} ({{group.level}}){% endif %}
        </strong>
        {% if group.role %} <span style="display: block">({{group.role}})</span>{% endif %}
      </a>
    </dd>
      {% endfor %}
    {% endfor %}
  </dl>

  <br style="clear: both"/>

  <div id="gmap" class="gmap" style="margin-top: 2em; height: 400px; box-shadow: 0 0 5px -2px black;"></div>

{% endblock %}

{% block javascripts %}
    {{ parent()}}    
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="{{ asset('js/jquery-gmap3-4.1/gmap3.js') }}"></script> 
    <script>
      $(document).ready(function() {

        $().gmap3('setDefault', {
          unit:'km',
          init:{
            zoom: 5
          }
        });

        $('#gmap').gmap3({
          action: 'addMarker',
          address: '12 rue des Frères Lumière 68093 Mulhouse CEDEX',
          options: {
            icon: new google.maps.MarkerImage('https://chart.googleapis.com/chart?chst=d_simple_text_icon_left&chld=|1|000|school|24|000|FFF')
          }
        });

        {% for info in user.contacts -%}
        {%- if info.type|slice(0, 4) == 'addr' -%}
        $('#gmap').gmap3({
          action: 'addMarker',
          address: '{{ info.value|replace({"\n": ' ', "\r" : ' '}) }}',
          options: {
            icon: new google.maps.MarkerImage('http://maps.gstatic.com/mapfiles/icon_green.png')
          }
        });
        {% endif -%}
        {%- endfor %}
      });
    </script>
{% endblock %}